### ISSUE TITLE
O2.6.1-2 Big Leaf Model (SDI)

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#152]
## Purpose
Implement a big leaf model into ClimaLSM. The goal of this is to (1) have an example demonstration of a canopy model running with ClimaLSM that we can learn from when we integrate the SPAC model and (2) to have a simple working canopy model which we can integrate with the soil model as a simple land model.

#151 first PR with parameterizations
#162 Compute surface albedo, emissivity and transpiration with canopy [closed as this was added into #163]
#163 Modularize canopy models
#175 Plant hydraulics only runs as part of the canopy (remove standalone option)
#181  update ozark experiment - soil hydrology + big leaf model
#185 plant vulnerability curves
#189 full canopy+soil
#238 zero lai support
#265 two-stream radiation
spatially varying and time varying parameter  - handled now in Issue #126 
#263 area index varies in time (site level)
#264 globally prescribed parameters that vary in time and space
#341 Adds prognostic temperature for the canopy
#368 #369 #276 Additional Fluxnet sites

## Cost/benefits/risks
Cost: developer time (Alexis, Katherine, Renato), there is a duplication of effort with what Yujie has already built
Benefit: We think this is a shorter route to a version of a canopy model + soil that we can couple to the atmosphere, and the simpler land surface model will likely be easier to debug. this will also be a "minimum working example" that we can build off of to incorporate the SPAC model instead. There is also an opportunity for us to learn about how these models work (which also spreads knowledge across the team instead of concentrated in a few people).
Risks: we really want this to be a stepping stone to running the physical land model with the SPAC model, and not viewed as an alternative.

## Producers
Alexis (primary developer), Katherine (developer), Renato (supervision, equation/science support)

## Components
Radiative transfer model (Beer's law) - we need to get fAPAR here
Photosynthesis model (C3 to start, Farquar model)
Stomatal conductance model (Medlyn)
API for integrating these with existing plant hydraulics model

## Inputs
This is a work in progress https://www.overleaf.com/8566116853pdxxskxjjsdh

## Results and deliverables
1. Create a working canopy model which we can run standalone mode.
2. Integrate the canopy model with the soil model, and drive with reanalysis data (Ozark test site or another). Clear demonstration of how to use atmospheric conditions to compute the necessary fluxes.
3. Run in a global setting (ingest parameter maps for LAI, Vcmax25, rooting depth)
4.  Use the existing climalsm interface to couple with the atmosphere in a global setting.
5. A tutorial for use, documentation, unit tests

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [x] A short doc with equations that we will implement. (https://www.overleaf.com/8566116853pdxxskxjjsdh)
- [x] Implement the parameterizations needed, keeping in mind that these will be swapped out for more complex versions: Beer's law for radiation, Farquar model for photosynthesis, parameter structs, and Medlyn conductance. #151 
- [x] Small PR to add Insolation parameters #165 
- [x] PR to update PrescribedAtmos to use P instead of rho, add concentration of co2, add zenith angle to PrescribedRadiation #167 
- [x] Write simple albedo and emissivity functions #163
- [x] Compute transpiration #163
- [x] Hooking up with plant hydraulics #163
- [x] Making a bit more modular (CanopyModel as RTModel, PhotosynthesisModel, etc...) #163, see also #175
- [x] Implement right hand side functions and update aux functions as needed #163
- [x] Hook up with soil model and test at ozark site. #181 
- [x] change retention curve and K(psi) for plant hydraulics #185 
- [x] Add Optimality model for VCmax #215 
- [x] Run with full soil model #189 
- [x] Run with correct surface fluxes (taking into account soil under canopy vs. bare soil) #341 #351 
- [WONT DO HERE; ENHANCEMENT] Add SIF model  - moved to https://github.com/CliMA/ClimaLand.jl/issues/595
- [x] Add PFTs https://github.com/CliMA/ClimaLand.jl/pull/493

...

## Reviewers
@braghiere @Yujie-W @cfranken @tapios @eviatarbach

**Comment by tapios** [comment]
This looks like a great stepping stone to me. A few additional points to consider:
* One important aspect we want to prototype is the handling of parameters and output, to create parameter-to-output maps that we can eventually invert to learn about parameters from data. So making this code compatible with ClimaParameters is important (you probably were planning this anyway). @eviatarbach's input here would be helpful, given his recent experience with the more complex biophysics model. 
* @eviatarbach has also used optimality-based functions for VCmax and learned functions for chlorophyll content. It would be good to include these here too. This will allow us to begin asking quantitative questions about what model complexity is necessary to fit (global) data. 
* What is the minimal model necessary to also simulate SIF in this relatively simple setting, which still has a photosynthesis model?

**Comment by kmdeck** [comment]
@eviatarbach could you add some notes about that model to the overleaf? Equations, what parameters are required, if they are constant over the globe or spatially varying (but constant in time), and if the model introduces any prognostic variables that we solve for via a diff eq. thank you!

Im not sure about your last point, @tapios, but as to the first one - yes, we'll use CLIMAParameters. Ill show Eviatar what we have been doing so far within ClimaLSM and we can adjust it if needed!

**Comment by Yujie-W** [comment]
> * What is the minimal model necessary to also simulate SIF in this relatively simple setting, which still has a photosynthesis model?

**[Short answer]**
One can emulate SIF with the simple RT models, but the bias could be too high.

Ray tracing canopy radiative transfer (RT) models are among the most complex models. The intermediate ones, such as what we use in the Land module, are to bin the leaf by the angular distribution. The simplest RT models are the two leaf scheme and one big leaf scheme.
However, big leaf models do not simulate hyperspectral RT, and thus cannot simulate SIF directly. What people did is to add an ad-hoc scaling based on leaf level photosynthesis and SIF. Yet, this emulated SIF does not contain any information about sun-sensor geometry, and may have considerable bias. For instance, if we assume the CliMA Land RT values are true values (blue dashed curve), the purple is that of big leaf RT, and the red is that of two leaf RT. All the simulations were done using Land RT in the figure below; the bias could be much higher if one uses big leaf RT to emulate the already biased SIF.

![image](https://user-images.githubusercontent.com/16584422/219712879-247b1745-05dd-44d4-b2a3-4d98c66d8efe.png)

**Comment by braghiere** [comment]
The minimal model to simulate SIF is a linear regression of GPP: 

SIF = a . GPP 

CARDAMOM-SIF uses an approach like this. Noting that the errors associated with this simple model can be substantial, as @Yujie-W showed.

**Comment by tapios** [comment]
> The minimal model to simulate SIF is a linear regression of GPP:
> 
> SIF = a . GPP
> 
> CARDAMOM-SIF uses an approach like this. Noting that the errors associated with this simple model can be substantial, as @Yujie-W showed.

How can we emulate what @Yujie-W did in a big leaf model? I.e., use his simulation of SIF without multiple layers in a canopy?

**Comment by Yujie-W** [comment]
[Here](https://www.sciencedirect.com/science/article/pii/S003442571930392X) is an example of how BEPS emulate SIF

**Comment by tapios** [comment]
> [Here](https://www.sciencedirect.com/science/article/pii/S003442571930392X) is an example of how BEPS emulate SIF

Thanks, @Yujie-W. This is worth keeping in mind to implement in a next stage of the big leaf model.
