### ISSUE TITLE
Performance roadmap

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaLand.jl#586]
```[tasklist]
- [x] `top_center_to_surface` allocates at every step - see https://github.com/CliMA/ClimaLand.jl/issues/615
- [ ] https://github.com/CliMA/ClimaLand.jl/issues/588
- [x] Remove `dss!` if not needed
- [x] Move to ClimaDiagnositcs to avoid the saving callback
- [ ] Address type instabilties in ClimaUtilities
- [x] Preallocate space for regridded fields, add `regridded_snapshot!` to ClimaUtilities
- [x] Check norm2
- [x] Boundary fluxes
- [x] update_aux in Biogeochem
```

Attached is a flamegraph for a GPU run for a bucket with resolution 100. This comes from the run introduced in https://github.com/CliMA/ClimaLand.jl/pull/577/files#diff-c59e565d751c44123440feac3f10d5aaf78e58080716fafa54176cdbe44b50cd, with a simulation length of 1 day.
![image](https://github.com/CliMA/ClimaLand.jl/assets/9167485/c3f9cc08-14ee-4b5c-9f7c-92ebf63340b0)

**Comment by Sbozzolo** [comment]
> the `top_center_to_surface` allocations will be reduced in #542 - see [changes](https://github.com/CliMA/ClimaLand.jl/pull/542/files#diff-97d55a93ad620f35722d4a76636f9d9e3dc16f08298f8f0247ce07c39a64af59R660-R677). I'm happy to move to a separate PR if preferred

Reduced or removed?

**Comment by juliasloan25** [comment]
We've implemented enough performance improvements for our current needs, so we can close this issue
