### ISSUE TITLE
O2.6.4 Spatially varying parameters - Canopy model

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#596]
## Purpose
To introduce code that allows us to set up spatially varying parameters which do not vary in time in the canopy model, and make use of them throughout the simulation. This will use the spatially varying parameter framework put in place by the completion of #126 and used to supply spatially varying parameters to the soil model by #485.

## Cost/benefits/risks
 - Costs:
   - Developer hours
   - Will require simplification of the canopy hydraulics model which will cost us the ability to set up multilayered canopy hydraulics
 - Benefits:
   - Provide a clean interface for varying parameters for the canopy model spatially
   - Unifies the way we handle spatially varying parameters for the canopy model regardless of the simulation domain.
 - Risks:
   - Could potentially result in performance issues for the canopy model.

## Producers
 - @Espeer5 to implement and @kmdeck to oversee

## Components
 - Simplification of the `PlantHydraulics` model to run only for the case of a big leaf model, without multiple layers to reduce data stored across space
 - Creation of a `biomassModel` submodule in the canopy
 - Refactoring of the canopy to place all relevant biomass parameters within the new biomass model
 - Integration of the `SpaceVaryingInput` function mechanism used in the soil model

## Results and deliverables
 - Canopy model running over spatially varying parameters
 - A tutorial demonstrating how to set up a canopy run with parameters varying across space
 - A series of tests verifying the canopy behavior when set up to vary spatially
 - A test to verify that the single layered plant hydraulics model produces the same output as the previous multilayered model for the case of a single layer

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [ ] BigLeaf-specific single layer plant hydraulics model
- [ ] Canopy Biomass refactoring
- [x] #723
- [ ] Creation of tests and tutorials for the spatially varying canopy model.

## Reviewers
 - @Espeer5
 - @kmdeck
 - @AlexisRenchon
 - @braghiere
