### ISSUE TITLE
Experiment scripts and plots for Paper I - Intro to land model

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#608]
## Purpose
This outlines and tracks PRs which add experiments and plotting of results for use in our paper introducing the land model [(read only link)](https://www.overleaf.com/read/qnxcgcwncxpk#721873).

## Components
Simulation scripts @kmdeck 
Diagnostics @AlexisRenchon 
Plotting @kmdeck (single site) @AlexisRenchon (global)
Performance @Sbozzolo 
Implicit solver @juliasloan25  

## Results and deliverables

High quality plots demonstrating the model output for:
- standalone soil: freeze/thaw, layered soil, and evaporation
- standalone soil+ snow: bare soil site (Barrows Alaska)
- integrated land model (soil/snow/canopy): ozark site (LWP during drought, GPP, soil water content, ET, etc)
- integrated land model (soil/snow/canopy): global run with ERA5 forcing - what plots?

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [ ] Upgrade all existing paper plots for soil to use CairoMakie: https://github.com/CliMA/ClimaLand.jl/pull/565 @kmdeck 
- [ ] Add global run of soil/canopy model: https://github.com/CliMA/ClimaLand.jl/pull/591 @kmdeck @Sbozzolo 
- [ ] Add bare soil site even if without snow: https://github.com/CliMA/ClimaLand.jl/pull/444 @kmdeck 
- [ ] Snow model https://github.com/CliMA/ClimaLand.jl/pull/147 @kmdeck for simplest possible model
- [ ] Improvements to snow model - Sarah Zhang, Andy Charbonneau
- [ ] Snow model integrated with soil @kmdeck 
- [ ] Snow model integrated with soil + canopy @kmdeck 
- [ ] Diagnostics @AlexisRenchon 
- [ ] Plotting of diagnostics @AlexisRenchon 
- [ ] Optimization of models @Sbozzolo 
- [ ] Plots showing computional performance of model (metrics TBD) @Sbozzolo 
- [ ] Plot demonstrating implicit solver - timestep vs conservation error @juliasloan25 ?

## Reviewers
@braghiere

**Comment by braghiere** [comment]
Thanks @kmdeck! I updated the list of plots in Results: integrated land model (soil/snow/canopy): global run with ERA5 forcing.

**Comment by AlexisRenchon** [comment]
Thanks @kmdeck! Here are some thoughts:
- I think eventually we should separate generating simulation outputs and plotting from those outputs (especially for global run, as we may run simulations on the cluster, and then make plots on local computer). I understand the next step is me working on diagnostics =) we should agree on standardized output file (netcdf probably, with long and short name of variables, units, etc. I think Gabriele has a framework for this)
- I am not sure where and how yet, but having a place where we gather plotting functions would be good for reproducibility. We currently have https://github.com/CliMA/ClimaLand.jl/blob/main/lib/ClimaLandSimulations/src/utilities/makie_plots.jl which contains plotting functions that take inputs and simulation outputs as arguments, and return a plot. This make it easier to remake the same plot with different inputs and outputs (e.g., different start and end date, or different site). We could have a discussion on the best place and practices to do this. It would be great to have a library of plots (and analysis) that improves over time and we can go back to it easily!

Note these are just thoughts and not a priority for the papers.

**Comment by juliasloan25** [comment]
I added a tasklist "Performance/implicit solver plots" listing the plots we discussed during the land meeting today. Here are the reference/example plots for the scaling information, from Renato and Gabriele:

<img src="https://github.com/CliMA/ClimaLand.jl/assets/51397186/271467d5-09e1-41fa-aed0-1a4395ab2efb" width="550"/>
<img src="https://github.com/CliMA/ClimaLand.jl/assets/51397186/2de979ea-1b52-47b0-99e5-542f8cb8029c" width="200"/>
