### ISSUE TITLE
Add global soil/canopy run forced by ERA5 data, with 1 degree resolution and reading in data every 3 hours

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#644]
```[tasklist]
### Tasks
- [x] Fix canopy fluxes when RAI = SAI = LAI = 0 https://github.com/CliMA/ClimaLand.jl/pull/641
- [x] Fix roundoff bug when LAI is very small in two stream scheme https://github.com/CliMA/ClimaLand.jl/issues/645 [WONT DO - CLIP LAI TO 0 IF LAI < 0.05]
- [ ] https://github.com/CliMA/ClimaLand.jl/issues/696
- [x] Add benchmark run https://github.com/CliMA/ClimaLand.jl/pull/591
```

**Comment by juliasloan25** [comment]
completed
