### ISSUE TITLE
Extend Vcmax to support `SpaceVaryingInput` 

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaLand.jl#723]
Towards spatially varying canopy parameters:

```[tasklist]
### Tasks
- [ ] Obtain Vcmax map, visualize it, possibly deal with ocean values/NaNs
- [ ] Add it to ClimaArtifacts
- [ ] Extend `FarquharParameters` to support `F <: Union{<: AbstractFloat, ClimaCore.Field}`
- [ ] Change `land.jl` in benchmarks to use `SpaceVaryingInput` and ClimaLand functions and tests that use `Vcmax`
```
