### ISSUE TITLE
Remaining to do for Diagnostics

### ISSUE THREAD

**Issue by AlexisRenchon** [CliMA/ClimaLand.jl#730]
- [x] Comprehensive tests #743 
- [x] Finalize docs #743 
- [x] Make sure carbon flux units are consistent, make a choice (kg or mol, CO2 or C) #731 
- [x] Runoff model: runoff variables are present or not depending on RunoffModel choice
- [x] Possibly, in define_diagnostics comments, add "2D" / "3D" or "surface only" / "subsurface" #734 
- [x] Finalize use of Diagnostics in all experiments and tests and docs tutorials (refactoring)
- [x] Bucket/EnergyHydrology do not define output_type and frequency #734 
- [ ] Make buildkite artifacts more navigable #874 
- [ ] Add one small integration test in `test` with a couple of diagnostics #874
