### ISSUE TITLE
Consistency in fluxes and setting radiative properties of land

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#777]
## OKR2.3.8:
"Prepare for coupled runs: ensure that we follow the flux and unit conventions set by the coupler. Compute bulk albedo and temperature of surface, set emissivity to 1."

## Units
- all energy fluxes are in J/m^2/s
- we store evaporation as a liquid water volume flux. The coupler converts the mass flux computed by atmos for us: https://github.com/CliMA/ClimaCoupler.jl/blob/59abc31b66ccb6d62a06fb86be9f0340fae4d4c0/experiments/ClimaEarth/components/land/climaland_bucket.jl#L211
- we store precipitation as a liquid water volume flux. The coupler converts a mass flux to volume flux for us right now: https://github.com/CliMA/ClimaCoupler.jl/blob/59abc31b66ccb6d62a06fb86be9f0340fae4d4c0/experiments/ClimaEarth/components/land/climaland_bucket.jl#L197
**Land to do: convert internally to volume fluxes**
- What units will carbon fluxes be in? (mass flux of C)

## Flux sign convention
We have followed the convention for fluxes that positive = towards atmos and negative = towards land. This applies for precipitation, SHF, LHF, evap, and everywhere in the land model, *except radiation*. 

**To do: change precip to be defined to be positive**

## Radiation internals for Land
For radiation, we have "LW_d" and "SW_d" in prescribed atmosphere runs. These are scalars, and indicate the magnitude of the downwelling radiation. They are always positive. We then compute "LW_u" and SW_u", which are the magnitude of the upwelling radiation, and hence are always positive. 

**To do: Change all instances of in/out to down/up.**

2. Internally, we also compute the net radiation per land component "R_n = downwelling - upwelling".  Hence this is positive if the land component is absorbing energy. Note that this is *opposite* the flux convention we use everywhere else, with negative indicating "towards land".
- ChosencConvention: R_n > 0 implies land absorbs energy. The net flux at the surface would then be SHF + LHF - R_n.

 **To do: make sure this convention is followed throughout**
## Coupled atmosphere runs - radiation:
- we will need SW_d in PAR and NIR wavelength bands currently, eventually we may have a more spectrally resolved model. Can the coupler carry out the conversion between the bands of the atmosphere model and of the land model?
- What sign convention will the downwelling SW fluxes follow?  **Answer: same as ours**
- we will need LW_d. What sign convention will this follow? **Answer: same as ours**
**Atmos wants a broadband albedo, emissivity, and a single temperature (see below)
Land will hand splitting SW into PAR and NIR by dividing by 2**

## Bulk surface properties
RRTMGP also requires the bulk properties of the land surface. We compute the net LW_u and SW_u (broadband) from all land components. there is therefore not a way to separate LW_u into emissivity and Temperature uniquely, so we set:
epsilon_sfc = 1 [note epsilon_soil and epsilon_canopy are not 1]
T_sfc = [LW_u/(epsilon_sfc*sigma)]^(1/4) [effective temperature, not the skin temperature]
alpha_sfc = SW_u/SW_d

**To do: implement. To do this properly, we need to store the fraction reflected, and not this number multiplied by SW_d. This is because at night SW_d is zero, but the albedo should not be zero**
```[tasklist]
### Tasks
- [ ] Upwell/downwelling notation consistency https://github.com/CliMA/ClimaLand.jl/pull/776
- [ ] Bulk land properties needed by atmos https://github.com/CliMA/ClimaLand.jl/pull/776
- [ ] Fix albedo to not be zero at night
- [ ] Sign convention for R_n https://github.com/CliMA/ClimaLand.jl/pull/827
- [ ] Precip and evaporation as mass fluxes
- [ ] SIgn of precip
- [ ] Documentation page https://github.com/CliMA/ClimaLand.jl/pull/827
```
