### ISSUE TITLE
Implement ClimaLand global calibration

### ISSUE THREAD

**Issue by AlexisRenchon** [CliMA/ClimaLand.jl#794]
```[tasklist]
- [x] 1 column, perfect model (done, link PR) #621
- [x] 1 column, observation, make sure prior sample is a large spread around target! (to do so, 1, identify correct parameters, and 2, their correct distribution - so that wide spread around target) #816
- [x] Global simulation (100s columns) with global bucket, LHF and SHF (ERA5), monthly, 1 year (multiple obs., multiple locations, write read climadiagnostics files, uses EKP Observations) #835
- [ ] Global simulation with land model
```

**Comment by AlexisRenchon** [comment]
Data (LHF and SHF that we calibrate on) needs to be in the same format as model output

**Comment by AlexisRenchon** [comment]
Note: we should change single site observation calibration a bit, it takes 2 hours right now (300 simulations run), we could save the figure but run it with less simulations to ensure it passes CI

**Comment by AlexisRenchon** [comment]
Land model:
What loss function? 
LHF, SHF, emissivity, SW, LW, (SIF, NEE, C fluxes)

**Comment by AlexisRenchon** [comment]
- Format: EKP vs. ClimaCalibrate
- Models: Bucket vs. LandModel
- Data: Observations vs. Perfect Model
- Scale: Single site vs. Multi-columns vs. Global

Possible KR:
- Create pipeline with EKP or ClimaCalibrate
- Demonstrate parameters recovery with Perfect Model
- Demonstrate X with observations

What we mean by Loss: 
- Different averaging period or other reduction of variables
- Different configuration, e.g., initialisation

Parameters:
- Correlations between parameters
- Parameters selection and distributions

Next to do: 
- Multiple variables stacked (ETKI, see comment above)
- Multiple columns (e.g., 100s, see above)
- Using netcdf diagnostics read and write


-

**Comment by AlexisRenchon** [comment]
(to do: add 2*sqrt(noise) as a band around target)

**Comment by AlexisRenchon** [comment]
Options: limits the amount of data by averaging over larger steps

**Comment by AlexisRenchon** [comment]
Think of informative features of the data that you want to capture such as seasonal amplitude, seasonal shifts, diurnal amplitude, etc. that are controlled by parameters...

Then you can make THAT your target as a function of params, and calibrate

**Comment by AlexisRenchon** [comment]
observational noise is standard deviation, i.e., covariance

**Comment by AlexisRenchon** [comment]
next steps:
- ClimaCalibrate for Bucket
- g(params) for full land model, global calibration

**Comment by AlexisRenchon** [comment]
when doing random locations on land, do we sample good representation of all landscapes

**Comment by AlexisRenchon** [comment]
only write LHF and SHF diagnostics
