### ISSUE TITLE
Implicit solver enhancements

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLand.jl#809]
## Purpose
In milestone [O2.3.6](https://github.com/CliMA/ClimaLand.jl/issues/135), we have implemented implicit solvers for RichardsModel, EnergyHydrologyModel, and SoilCanopyModel. As we developed these, we identified some areas for improvement that we want to address at some point, as well as ideas for improved stability that may or may not be necessary. These are documented here.

## Cost/benefits/risks
costs: developer time
benefits: increased simulation stability, decreased code duplication, more robust code
risks: potential regressions if we alter equations

## Producers
@juliasloan25 @kmdeck 

## Components
- more accurate jacobian approximations for increased simulation stability
- code cleanup

## Inputs
Implicit solvers introduced in #135 

## Results and deliverables
Maintain or improve stability of implicitly-stepped experiments

## Reviewers
@juliasloan25 @kmdeck @dennisYatunin (PRs)
@tapios @cmbengue (SDI review)

## Tasks
```[tasklist]
### general implicit stepping
- [ ] #659
- [ ] #661
```

```[tasklist]
### SoilCanopyModel
- [ ] #782
```

```[tasklist]
### EnergyHydrologyModel
- [ ] #662
- [ ] include boundary condition contributions (if needed)
- [ ] include contribution from drhoe_int / dtheta_l (if needed)
- [ ] understand how to treat soil phase change implicitly
```

```[tasklist]
### RichardsModel
- [ ] smooth derivative dPsi/dtheta at theta = \nu (if needed)
```

**Comment by tapios** [comment]
This looks good and thorough to me (though I say that without being familiar with all items here).
