### ISSUE TITLE
O2.5.1: Run the global soil/canopy/snow model forced by ERA5 data for 10-20 years

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLand.jl#859]
## Purpose

> O2.5.1: Run the global soil/canopy/snow model forced by ERA5 data for 10-20 years and demonstrate stability with a timestep of ~10 minutes and 12 SYPD

This works towards O2.5:
> O2.5 Couple the land surface model with soil/canopy/snow to atmosphere model and update surface flux computations to enable fractional cover with land properties (e.g., snow and canopy). [Possibly move up if needed for good AMIP.]

Before we couple the "full" land model (soil+canopy+snow) with the atmosphere, we need to make sure that it can run on decadal timescales independently.

## Cost/benefits/risks
- costs: developer time, HPC resources for long simulations
- benefits: longer simulations will allow more comparisons to other land models, and more scientific opportunities, in addition to preparing for coupling to atmos
- risks: need to access large quantities of ERA5 data for forcing from NCAR Derecho cluster; we have limited computing time on Derecho and want to use it for calibration, so we should be cautious of running frequent long runs on Derecho

## Producers
@juliasloan25
@kmdeck 

## Components
- set up pipeline on Derecho
- access data, efficiently handle large quantities and long time series of data

## Inputs
- existing 1-year ERA5-forced global runs
- data on NCAR Derecho cluster

## Results and deliverables
- stable global full land model forced by ERA5 data for 10-20 years with timestep ~10 minutes and 12 SYPD

## Reviewers
@juliasloan25 @kmdeck @Sbozzolo  (PRs)
@tapios @braghiere (SDI)
```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/ClimaLand.jl/issues/902
- [ ] https://github.com/CliMA/ClimaLand.jl/issues/904
- [ ] https://github.com/CliMA/ClimaLand.jl/issues/953
```

**Comment by tapios** [comment]
Looks good. (As for the other SDI, we should update the time variables first, so that we can run for decades without running into float32 problems.)

**Comment by kmdeck** [comment]
This depends on these PRs:
https://github.com/CliMA/ClimaLand.jl/pull/834 (adds snow to soil + canopy)
https://github.com/CliMA/ClimaLand.jl/pull/856 (changes boundary condition and initial condition)

which hopefully will be merged in the next week :)
